### ISSUE TITLE
Request: Add parameter for mana cost per second

### ISSUE THREAD

**Issue by CravenCraft** [SiverDX/pufferfish_unofficial_additions#1]
Hey, love this mod and am using it for my modpack. Was wondering if it would be possible to add either a **parameter** or **source type** for **mana per second** as that seems to be the one thing that's slightly unbalanced.

For example:
Casting a spell that is single use and costs 50 mana will always be preferrable to casting a spell that costs 12 mana/s since the **mana_cost** parameter only looks at how much mana a spell will initially cost and not how much it could potentially cost over the time of its casting.

**Comment by SiverDX** [comment]
While looking at the code I noticed that I might need to change some stuff
That change would fix the fact that cancelling a spell with a charge time giving you free experience

But it also means that continous spells would trigger the exp reward for each tick
The plan would be to add a parameter which contains the amount of expected ticks (which would be 1 for instant or charged casts)

Example:

[17:57:44] [Server thread/DEBUG] [de.ca.pu.PUA/]: Context of [pufferfish_unofficial_additions:spell_casting]:
- Caster: [ServerPlayer['Dev'/192, l='ServerLevel[New World]', x=52.76, y=72.00, z=-39.42]]
- Item: [irons_spellbooks:scroll]
- School: [irons_spellbooks:ender]
- Spell: [irons_spellbooks:starfall]
- Level: [2 | min: 1 | max: 6]
- Rarity: [1]
- Mana cost: [6]
- Mana cost per second: [12]
- Cast duration: [160]
- Cast charge time: [0]
- Cooldown: [320]
- Expected ticks: [16]
- Experience gained: [0]

Cast duration / charge time and cooldown are in ticks
Could also divide it myself by 20 to show it in seconds

---

Any input on this?

**Comment by CravenCraft** [comment]
I haven't delved too much into irons code or your code, but maybe it could be possible to check each tick if the previous mana is less than the current mana, and that difference can be the amount of xp the player receives? 

That way you don't necessarily need to know the amount of mana each spell will cost, just check what mana is being drained per tick check. As long as the player is casting or trying to cast a spell then this check could be actively happening and then end when the spell is over to ensure there isn't a performance impact

**Comment by SiverDX** [comment]
I already know the mana per second it's in the debug output I posted 

I was asking about a different beheaviour I'll have to change (related to a bug with charged / long casting)

im currently using the event iron provides it doesn't happen per tick, just once when the player initiated a cast (which will change to fix this bug)

it could be correct to give xp per continuous casting tick
it could also be correct to only do it once

not sure atm
kinda favoring per tick 

and then let people divide the xp by the amount of expected ticks if they want 

could be a problem if their xp reward goes below 1 due to that (though they could use max())

**Comment by SiverDX** [comment]
there is also the thing about scrolls
they don't consume mana (same for swords if the config for that is disabled)

should the mana cost therefor be 0 or should it still show the theoretical mana cost of the spell
(and the user can check for scrolls to handle the logic differently)

**Comment by CravenCraft** [comment]
Ah, my bad didn't notice that in the output log. Yeah, the event only triggering once at the beginning is definitely an issue with those continuous casts and any cast that requires a build up like you said. 

Hm, maybe something like:

- Cast event triggers
- Enter a loop that continues for at least maybe 20 ticks?
- in the loop check for current vs previous mana. Have a variable that adds the difference to the total cost. 
- Continue the loop if the current mana is less than the previous mana. Break the loop if the current and previous are the same (or it's 0). 
- Once out of the loop get the total mana cost. 

The loop would only last for as long as the player's mana is being drained, it would only trigger on the spell cast event, and this theoretically fixes the bug with the charged/long casting. 

In regards to the scrolls. I think having a config to enable mana cost for scrolls would be ideal. By default it could be true if the player has your attribute that doesn't consume the scroll on use enabled. Seems like the most balanced approach otherwise plays would just keep the scrolls they want in their inventory since mana would be a non-issue.

**Comment by SiverDX** [comment]
the question was more on what would be more correct tbh
charged cast and instant only trigger once, thats also how it should work i guess

but for continuos casting
in my opinion its kinda correct if it triggers per cast tick (where it casts the spell and consumes the mana)
(which could be e.g. 10 ticks if you can cast it for 5 seconds)
but there could be also an argument that it should only trigger once

at the moment all three types trigger once
but with the change to fix the charge cast cancel bug i could put it at a spot where continuos triggers per spell tick (not game tick but actually-being-casted-tick)

---

not sure what you meant with the scroll part
i meant it for the experience source - since scrolls dont consume mana should the mana cost parameter for them be 0 or the mana cost of the spell (if it was e.g. in a spell book)

**Comment by CravenCraft** [comment]
Gotcha. Yeah, I think having the continuous casting to trigger per spell cast tick would be a good middle ground to resolve the issue. That's kinda where I was getting at as well (just a different approach I guess). 

Yeah sorry about the scroll. Misread that too. I thought you meant that you were going to make it to where the scrolls were going to cost mana. Yeah, I think that if scrolls don't drain mana then they shouldn't give you experience.

**Comment by SiverDX** [comment]
Added in 1.2.0
